[package]
name = "advent_of_code_2025"
version = "0.1.0"
edition = "2024"


[profile.develop]
inherits = "release"
overflow-checks = true
incremental = true

[profile.release]
debug = true

[dependencies]
aoc_lib = { git = "https://github.com/Measter/aoc_lib" }
color-eyre = "0.6.5"
